import './globals.css'
  import { ReduxProvider } from '../lib/provider'
  import Footer from '../components/Footer'
  import Navbar from '../components/Navbar'

export const metadata = {
  title: 'Easy College',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <ReduxProvider>
          {children}
        </ReduxProvider>
        <Footer />
      </body>
    </html>
  )
}
